name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: dockerv1.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image with tags v2 and latest
      run: |
        docker build . \
          -t dockerv1.azurecr.io/my-image-name:v2 \
          -t dockerv1.azurecr.io/my-image-name:latest

    - name: Push Docker image (v2 and latest)
      run: |
        docker push dockerv1.azurecr.io/my-image-name:v2
        docker push dockerv1.azurecr.io/my-image-name:latest

